#!/bin/bash
if ! which xgettext &> /dev/null; then
  echo xgettext is missing on your system!
else
  xgettext -L php -k__ -k_e -o messages.pot ../aigaionengine/*/*.php ../aigaionengine/*/*/*.php ../aigaionengine/*/*/*/*.php
fi
